### ISSUE TITLE
Move hard coded values to parametrized

### ISSUE THREAD

**Issue by gvillafanetapia** [MuttData/pharmacy#7]
First step could be to move it to a parameters.php file or something.

Then talk to Adam and push it into a table in Mysql.

**Comment by gvillafanetapia** [comment]
Where are we standing on this?

**Comment by JDSanto** [comment]
ATM the only couple of things that could be parametrized, are already in the constants file:
- `SIG_PARSER_FIXED_DRUGNAMES`, which for each drug name gives the qty_per_day to do an early return for that drug.
- `SIG_PARSER_CONF_SCORE_CUTOFF`, which is used to ignore results for really low confidence scores values and return a fixed `qty_per_day = 1`. This one should be removed once the confidence score is visible to a human, and do a manual intervention.

Other than that, I don't see anything else to be left as a parameter, other than the "excess over 6" for `sig_qty_per_day`. I'll add it shortly
